# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://fraank.de" # the url of your github pages

# site information used in page title, meta data etc.
title: "fraank"
description: Frank Cieslik

# color theme for links
theme-color: green

# homepage information
author: Frank Cieslik
author-bio: founder and software engineer
author-image: fraank.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/fraank
facebook: https://facebook.com/fraank
instagram: https://instagram.com/fraank
github: https://github.com/fraank
linkedin: https://linkedin.com/fraank
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "build with @fuxlab"
footer-msg-link: https://fuxlab.com

# google analytics
google-analytics: 'UA-131604694-1'

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
